[build-system]
requires = ["setuptools>=68", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "tensorflow"
version = "2.16.2.post1"                 # чуть новее официальной 2.16.2
description = "Alias: tensorflow -> tensorflow-rocm"
requires-python = ">=3.9"
dependencies = ["tensorflow-rocm==2.16.2"]

[tool.setuptools]
# Никаких модулей/пакетов намеренно
py-modules = []
